# Generated by Django 3.1b1 on 2020-10-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Projects_Completed', models.IntegerField(default=0)),
                ('clients', models.IntegerField(default=0)),
                ('Coffee', models.IntegerField(default=0)),
                ('Professionals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='servicese/')),
                ('description', models.TextField(max_length=110)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-id'],
            },
        ),
    ]
