# Generated by Django 3.1.2 on 2020-10-13 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20201013_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='iconn',
            new_name='icon',
        ),
    ]
